[project]
name = "mcp-isitdown-service"
version = "0.0.2"
description = "An MCP server that checks if a website is currently down by querying the website isitdownrightnow.com"
authors = [
    { name = "Really Him", email = "hesreallyhim@proton.me" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "mcp[cli]>=1.3.0",
    "httpx>=0.26.0",
]

[tool.pyright]
typeCheckingMode = "basic"
